import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import { Toaster } from "react-hot-toast";
import Image from "next/image";
import bgImage from "@/app/assets/bgImage.jpeg";
import banner from "@/app/assets/topBanner.jpeg";
// const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "300", "500", "700"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "IPGA",
  description: "Generated by STORY",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="manifest" href="manifest.json" />
      <body className={`${montserrat.className}`}>
        <div>
          <Toaster />
        </div>
        <Image
          src={bgImage}
          className="object-cover absolute h-full w-full z-10"
          fill
          alt=""
        />

        <div className="bg-black bg-opacity-60 h-full w-full absolute z-20"></div>
        {/* <div className="absolute top-0 left-0 h-[8vh] w-full z-30">
          <Image
            fill
            src={banner}
            className="object-contain absolute top-0 left-0 z-30"
            alt=""
          />
        </div> */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
